version: '3.8'

services:
  heatmap-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
